using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FullContact.Domain.Enum
{
    /// <summary>
    /// Below is a list of type ids for photos, socialProfiles, and icons returned by the person method.
    /// </summary>
    public enum SocialProfileType
    {
        Twitter = 0,
        Linkedin = 1,
        AboutMe = 2,
        GoogleProfile = 3,
        Quora = 4,
        Foursquare = 5,
        Youtube = 6,
        Picasa = 7,
        Plancast = 8,
        Klout = 9,
        Flickr = 10,
        Gravatar = 11,
        GitHub = 12,
        Facebook = 13,
        Pinterest = 14,
        Google = 15,
        Instagram = 16,
        AngelList = 17,
        Xing = 18,
        Tumblr = 19,
        GooglePlus = 20,
        Amplify = 21,
        AolChat = 22,
        Bebo = 23,
        BitBucket = 24,
        Blippy = 25,
        Crunchbase = 26,
        Delicious = 27,
        Digg = 28,
        Disqus = 29,
        Dribble = 30,
        Flavorsme = 31,
        Friendster = 32,
        Gdgt = 33,
        GetSatisfaction = 34,
        Hackernews = 35,
        Hunch = 36,
        Hyves = 37,
        Identica = 38,
        IntenseDebate = 39,
        LastFM = 40,
        LiveJournal = 41,
        Meetup = 42,
        Mixi = 43,
        Ohloh = 44,
        Vk = 45,
        Plaxo = 46,
        Qik = 47,
        Reddit = 48,
        ReverbNation = 49,
        Other = 50,
        Shelfari = 51,
        SlideShare = 52,
        SoundCloud = 53,
        StackOverflow = 54,
        StumbleUpon = 55,
        Tripit = 56,
        Vimeo = 57,
        Weibo = 58,
        Wordpress = 59,
        Yelp = 60,
        Academiaedu = 61,
        Bandcamp = 62,
        Behance = 63,
        BlipFM = 64,
        Blogger = 65,
        DandyId = 66,
        DeviantArt = 67,
        Diigo = 68,
        DoYouBuzz = 69,
        EConsultancy = 70,
        FacebookChat = 71,
        FriendFeed = 72,
        FullContact = 73,
        GetGlue = 74,
        Gist = 75,
        GoodReads = 76,
        GTalkChat = 77,
        Hi5 = 78,
        HypeMachine = 79,
        IcqChat = 80,
        Imdb = 81,
        IrcChat = 82,
        Lanyrd = 83,
        Meadiciona = 84,
        Mixcloud = 85,
        MySpace = 86,
        Orkut = 87,
        Pandora = 88,
        PinBoard = 89,
        Plurk = 90,
        Renren = 91,
        Scribd = 92,
        Skype = 93,
        SmugMug = 94,
        StackExchange = 95,
        Steam = 96,
        Tagged = 97,
        TypePad = 98,
        Keybase = 99
    }
}
